# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='registered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIRMED', 'Not Confirmed'), ('CONFIRMED', 'Confirmed'), ('WAITING_LIST', 'Waiting List')], default='NOT_CONFIRMED', max_length=20),
        ),
    ]
