# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_auto_20170801_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('recipients', models.CharField(max_length=100)),
                ('sent_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inscription',
            name='status',
            field=models.CharField(choices=[('NOT_CONFIRMED', 'Not Confirmed'), ('CONFIRMED', 'Confirmed'), ('WAITING_LIST', 'Waiting List'), ('CANCELED', 'Canceled')], default='NOT_CONFIRMED', max_length=20, verbose_name='Status'),
        ),
    ]
