# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_auto_20170802_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='type',
            field=models.CharField(choices=[('SUBMISSION_CONFIRMATION', 'Submission Confirmation'), ('INSCRIPTION_CONFIRMATION', 'Inscription Confirmation')], default='INSCRIPTION_CONFIRMATION', max_length=30),
        ),
    ]
