# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_auto_20170805_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Inscription', verbose_name='Inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=20, verbose_name='Identification')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Location', verbose_name='Location')),
            ],
        ),
        migrations.AddField(
            model_name='inscriptionslot',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.Slot', verbose_name='Slot'),
        ),
    ]
