# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-03 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_auto_20170917_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='accepted_newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inscription',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
    ]
