# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-01 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0013_messagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='accepted_newsletter',
            field=models.BooleanField(default=False, verbose_name='Newsletter'),
        ),
    ]
