# Generated by Django 2.2.3 on 2019-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0015_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='total_places',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Places'),
        ),
    ]
