# Generated by Django 2.2.3 on 2019-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0016_edition_total_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagehistory',
            name='type',
            field=models.CharField(choices=[('SUBMISSION_CONFIRMATION', 'Submission Confirmation'), ('INSCRIPTION_CONFIRMATION', 'Inscription Confirmation'), ('WAITING_LIST', 'Waiting List'), ('INSTRUCTIONS', 'Instructions'), ('CANCELATION', 'Cancelation')], default='INSCRIPTION_CONFIRMATION', max_length=30),
        ),
    ]
